# Combo settings (auto-updated by `just _parse_combos`)
CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=8
CONFIG_ZMK_COMBO_MAX_KEYS_PER_COMBO=3

# Sleep timeout 30min (30*60*1000ms)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# Bluetooth tweaks
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
